# Copyright Â© 2025-26 l5yth & contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Production overrides for docker-compose.yml
services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
      target: production
    environment:
      DEBUG: 0
    restart: always

  web-bridge:
    build:
      context: .
      dockerfile: web/Dockerfile
      target: production
    environment:
      DEBUG: 0
    restart: always

  ingestor:
    build:
      context: .
      dockerfile: data/Dockerfile
      target: production
    environment:
      DEBUG: 0
    restart: always

  ingestor-bridge:
    build:
      context: .
      dockerfile: data/Dockerfile
      target: production
    environment:
      DEBUG: 0
    restart: always
